# Generated by Django 4.2.4 on 2023-09-11 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('h_number', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('res_pic_url', models.URLField(blank=True, db_column='pic_url', max_length=512, null=True)),
                ('res_type', models.CharField(max_length=128)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=512, null=True)),
                ('facebook', models.URLField(blank=True, max_length=512, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='restaurants_app.address')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restaurants_app.restaurant')),
            ],
            options={
                'db_table': 'restaurant_rating',
            },
        ),
        migrations.CreateModel(
            name='RestaurantDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField()),
                ('dish_pic_url', models.URLField(blank=True, db_column='pic_url', max_length=512, null=True)),
                ('dish_type', models.CharField(blank=True, max_length=128, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restaurants_app.restaurant')),
            ],
            options={
                'db_table': 'restaurant_dishes',
            },
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('dish', models.ForeignKey(blank=filter, on_delete=django.db.models.deletion.RESTRICT, to='restaurants_app.restaurantdish')),
            ],
            options={
                'db_table': 'dish_rating',
            },
        ),
    ]
