# Generated by Django 4.2.4 on 2023-09-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('res_pic_url', models.URLField(db_column='pic_url', max_length=512, null=True)),
                ('res_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dish_pic_url', models.URLField(db_column='pic_url', max_length=512, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restaurants_app.restaurant')),
            ],
            options={
                'db_table': 'restaurant_dishes',
            },
        ),
    ]
