# Generated by Django 4.2.4 on 2023-08-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
